version: '3.7'
services:
    app:
        build: ./
        env_file:
            - .env
        working_dir: /usr/src/myapp
        command: tail -f /dev/null
        volumes:
            - .:/usr/src/myapp
        links:
          - db
    db:
        image: mariadb
        env_file:
            -   .env
        ports:
          - 3306:3306
