version: '3.7'
services:
    app:
        build: ./
        working_dir: /usr/src/myapp
        command: tail -f /dev/null
        environment:
            docker: "true"
        volumes:
            - .:/usr/src/myapp
        links:
          - db
    db:
        image: mariadb
        restart: always
        ports:
          - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: 201125
